# Config file for automatic testing at travis-ci.org
language: python

services:
  - postgresql
env:
  global:
    PYTEST_ADDOPTS="--cov-append"

matrix:
  include:
    # Python version is just for the look on travis.
    - python: 3.6
      env: TOX_ENV=py36-django111,py36-django20,py36-django21,py36-django22

    - python: 3.7
      env: TOX_ENV=py37-django111,py37-django20,py37-django21,py37-django22

    - python: 3.8
      env: TOX_ENV=py38-django111,py38-django20,py38-django21,py38-django22

    - python: 3.8
      env: TOX_ENV=linters

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
